-- AWS基礎・応用クイズ シードデータ（選択肢シャッフル修正版）
-- 実行例: docker exec -i mysql mysql -u root -p myapp < db/seed-quiz-aws.sql

SET NAMES utf8mb4;

-- --------------------------------------------------------
-- 1. カテゴリIDを動的に決定して登録
-- --------------------------------------------------------

-- 既存の 'aws-basic' があればそのIDを、なければ MAX(id)+1 を @cat_id にセット
SET @target_slug = 'aws-basic';
SELECT @cat_id := id FROM quiz_category WHERE slug = @target_slug;

-- まだ存在しない場合、新しいIDを発番
SET @cat_id = COALESCE(@cat_id, (SELECT COALESCE(MAX(id), 0) + 1 FROM quiz_category));

-- カテゴリを登録
INSERT IGNORE INTO quiz_category (id, slug, category_name, author_id, description, display_order)
VALUES (@cat_id, @target_slug, 'AWS基礎・実践', 1, 'AWSの主要サービス（EC2, S3, RDS等）から、Amazon IVSなどのメディアサービスまで幅広く出題します。', @cat_id);


-- --------------------------------------------------------
-- 2. クイズデータの登録準備
-- --------------------------------------------------------

-- 既存の quiz の最大 id の次から採番開始位置を決定
SELECT @quiz_start := COALESCE(MAX(id), 0) + 1 FROM quiz;

-- AUTO_INCREMENT をリセット
SET @alter_sql = CONCAT('ALTER TABLE quiz AUTO_INCREMENT = ', @quiz_start);
PREPARE stmt FROM @alter_sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;


-- --------------------------------------------------------
-- 3. クイズ本体の登録（category_id には @cat_id を使用）
-- --------------------------------------------------------

INSERT INTO quiz (slug, category_id, author_id, question, explanation) VALUES
-- 1-45: General AWS
('aws-ec2-basic', @cat_id, 1, 'AWSクラウド上でサイズ変更可能なコンピューティングキャパシティを提供するサービスは？', '正解はAmazon EC2 (Elastic Compute Cloud)です。仮想サーバーを数分で起動し、必要に応じてスケールアップ・ダウンが可能です。'),
('aws-s3-storage-type', @cat_id, 1, 'Amazon S3 (Simple Storage Service) はどのタイプのストレージサービスか？', '正解はオブジェクトストレージです。ファイルシステム（ブロックストレージ）とは異なり、データをオブジェクトとしてキー（Key）と値（Value）で管理し、スケーラビリティと耐久性に優れています。'),
('aws-rds-managed', @cat_id, 1, 'Amazon RDSを使用する主な利点は何か？', '正解はデータベース管理タスク（パッチ適用、バックアップ、スケーリングなど）の自動化です。これにより、開発者はインフラ管理ではなくアプリケーション開発に集中できます。'),
('aws-lambda-serverless', @cat_id, 1, 'サーバーのプロビジョニングや管理なしでコードを実行できるAWSのサービスは？', '正解はAWS Lambdaです。イベント発生時のみコードを実行し、実行時間に対してのみ課金されるサーバーレスコンピューティングサービスです。'),
('aws-vpc-isolation', @cat_id, 1, 'AWSクラウド内に論理的に分離された仮想ネットワーク環境を作成するサービスは？', '正解はAmazon VPC (Virtual Private Cloud)です。IPアドレス範囲、サブネット、ルートテーブル、ネットワークゲートウェイなどを完全に制御できます。'),
('aws-iam-role', @cat_id, 1, 'AWSリソースに対して、一時的なセキュリティ認証情報を付与するためのIAMエンティティは？', '正解はIAMロールです。IAMユーザーとは異なり、特定の人物に関連付けられるものではなく、EC2インスタンスやLambda関数などのAWSリソースや、外部IDに対して一時的な権限を委任するために使用されます。'),
('aws-s3-glacier', @cat_id, 1, 'データの長期アーカイブとバックアップに適した、低コストなS3ストレージクラスは？', '正解はAmazon S3 Glacierです。取り出しに数分から数時間かかる場合がありますが、非常に低コストでデータを保存できます。'),
('aws-cloudfront-cdn', @cat_id, 1, '動画やアプリケーションなどのコンテンツを、低レイテンシーで世界中のユーザーに配信するためのCDNサービスは？', '正解はAmazon CloudFrontです。世界中に配置されたエッジロケーションを使用してコンテンツをキャッシュし、ユーザーに最も近い場所から配信します。'),
('aws-route53-dns', @cat_id, 1, '可用性と拡張性に優れたクラウドDNS（ドメインネームシステム）ウェブサービスは？', '正解はAmazon Route 53です。ドメイン登録、DNSルーティング、ヘルスチェックなどの機能を提供します。'),
('aws-dynamodb-nosql', @cat_id, 1, 'どのような規模でも1桁ミリ秒のパフォーマンスを実現する、フルマネージドNoSQLデータベースサービスは？', '正解はAmazon DynamoDBです。キーバリュー型およびドキュメント型のデータモデルをサポートし、自動スケーリング機能を備えています。'),
('aws-elb-load-balancing', @cat_id, 1, 'アプリケーションへのトラフィックを複数のターゲット（EC2インスタンスなど）に自動的に分散させるサービスは？', '正解はElastic Load Balancing (ELB)です。耐障害性を高め、アプリケーションの可用性を維持するために不可欠です。'),
('aws-autoscaling', @cat_id, 1, '需要に応じてEC2インスタンスの数を自動的に増減させる機能は？', '正解はAmazon EC2 Auto Scalingです。トラフィックの増減に合わせてキャパシティを調整し、コストの最適化と可用性の維持を実現します。'),
('aws-cloudwatch-monitor', @cat_id, 1, 'AWSリソースとアプリケーションの監視、ログ収集、アラーム設定を行うサービスは？', '正解はAmazon CloudWatchです。CPU使用率などのメトリクスを監視し、設定した閾値を超えた場合に通知を送ったりアクションを実行したりできます。'),
('aws-cloudtrail-audit', @cat_id, 1, 'AWSアカウント内でのAPI呼び出しを記録し、ガバナンスとコンプライアンス監査を支援するサービスは？', '正解はAWS CloudTrailです。「誰が」「いつ」「どのリソースに対して」「何をしたか」という操作履歴を記録します。'),
('aws-sqs-message', @cat_id, 1, '分散アプリケーション間でメッセージを非同期に送受信するための、完全マネージド型メッセージキューイングサービスは？', '正解はAmazon SQS (Simple Queue Service)です。コンポーネント間の結合を疎（疎結合）にし、耐障害性を向上させます。'),
('aws-sns-pubsub', @cat_id, 1, 'アプリケーションからの通知（プッシュ通知、SMS、Emailなど）を配信するためのPub/Subメッセージングサービスは？', '正解はAmazon SNS (Simple Notification Service)です。トピックを作成し、そこにサブスクライブしているエンドポイントに対してメッセージを一斉配信できます。'),
('aws-elasticache-memory', @cat_id, 1, 'RedisまたはMemcachedと互換性のある、フルマネージド型のインメモリデータストアサービスは？', '正解はAmazon ElastiCacheです。データベースの読み取り負荷を軽減し、アプリケーションの応答速度を向上させるために使用されます。'),
('aws-aurora-db', @cat_id, 1, 'MySQLおよびPostgreSQLと互換性があり、クラウド向けに構築された高性能なリレーショナルデータベースは？', '正解はAmazon Auroraです。商用データベースと同等のパフォーマンスと可用性を、オープンソースデータベースのコストで提供します。'),
('aws-kms-encryption', @cat_id, 1, 'データの暗号化に使用される暗号化キーの作成と管理を行うサービスは？', '正解はAWS KMS (Key Management Service)です。EBSボリュームやS3バケットなどのAWSサービスと統合されており、簡単に暗号化を実装できます。'),
('aws-shared-responsibility', @cat_id, 1, '「責任共有モデル」において、AWSが責任を持つ範囲はどれか？', '正解は「クラウド自体のセキュリティ（Security of the Cloud）」です。これにはハードウェア、ソフトウェア、ネットワーク、物理的な施設のセキュリティが含まれます。ユーザーは「クラウド内のセキュリティ（Security in the Cloud）」に責任を持ちます。'),
('aws-region-az', @cat_id, 1, 'AWSのインフラストラクチャにおいて、地理的に離れた領域を「リージョン」と呼ぶが、そのリージョン内に存在する独立した電源や冷却装置を持つデータセンター群を何と呼ぶか？', '正解はアベイラビリティーゾーン (AZ)です。複数のAZにリソースを分散配置することで、高い可用性と耐障害性を実現します。'),
('aws-ebs-block', @cat_id, 1, 'EC2インスタンスにアタッチして使用する、永続的なブロックストレージボリュームは？', '正解はAmazon EBS (Elastic Block Store)です。OSやデータベースの保存領域として使用され、インスタンスが停止してもデータは保持されます。'),
('aws-efs-file', @cat_id, 1, '複数のEC2インスタンスから同時にマウント可能な、フルマネージド型ファイルストレージサービスは？', '正解はAmazon EFS (Elastic File System)です。Linuxインスタンス用の共有ファイルストレージとして、自動的に拡張・縮小します。'),
('aws-shield-ddos', @cat_id, 1, 'DDoS攻撃からAWS上で実行されるアプリケーションを保護するマネージドサービスは？', '正解はAWS Shieldです。Standard（無料）とAdvanced（有料）があり、Standardは全てのAWS顧客に自動的に適用されます。'),
('aws-waf-firewall', @cat_id, 1, 'Webアプリケーションへの一般的な攻撃（SQLインジェクションやXSSなど）を防ぐためのファイアウォールサービスは？', '正解はAWS WAF (Web Application Firewall)です。CloudFrontやALBに適用し、悪意のあるトラフィックをブロックするルールを定義できます。'),
('aws-inspector-security', @cat_id, 1, 'EC2インスタンスの脆弱性やセキュリティ上のベストプラクティスからの逸脱を自動的に評価するサービスは？', '正解はAmazon Inspectorです。セキュリティ評価を自動化し、修正が必要な箇所の特定を支援します。'),
('aws-trusted-advisor', @cat_id, 1, 'コスト最適化、パフォーマンス、セキュリティ、耐障害性の観点から、AWS環境をチェックし推奨事項を提供するサービスは？', '正解はAWS Trusted Advisorです。使用していないリソースの削除や、セキュリティグループの設定ミスなどを指摘してくれます。'),
('aws-cost-explorer', @cat_id, 1, 'AWSのコストと使用状況を可視化し、分析するためのツールは？', '正解はAWS Cost Explorerです。グラフや表を使用して支出の傾向を把握し、将来のコストを予測することができます。'),
('aws-budgets-alert', @cat_id, 1, '設定した予算を超えそうになった場合にアラートを通知するサービスは？', '正解はAWS Budgetsです。コストや使用量が設定した閾値を超えた際に、SNSやメールで通知を受け取れます。'),
('aws-organizations-mgmt', @cat_id, 1, '複数のAWSアカウントを一元管理し、請求の一括化やポリシーの適用を行うサービスは？', '正解はAWS Organizationsです。組織単位（OU）を作成してアカウントを階層管理し、SCP（サービスコントロールポリシー）でアクセス制限を適用できます。'),
('aws-ecs-container', @cat_id, 1, 'Dockerコンテナをサポートする、拡張性の高いコンテナ管理サービスは？', '正解はAmazon ECS (Elastic Container Service)です。EC2またはFargateを起動タイプとして選択し、コンテナ化されたアプリケーションを実行・管理します。'),
('aws-fargate-serverless-container', @cat_id, 1, 'サーバーの管理なしでコンテナを実行できる、ECSおよびEKS向けのサーバーレスコンピューティングエンジンは？', '正解はAWS Fargateです。基盤となるEC2インスタンスを管理する必要がなく、コンテナレベルでのリソース指定が可能です。'),
('aws-eks-kubernetes', @cat_id, 1, 'AWS上でKubernetesを実行するためのマネージドサービスは？', '正解はAmazon EKS (Elastic Kubernetes Service)です。KubernetesのコントロールプレーンをAWSが管理し、既存のKubernetesツールとの互換性を提供します。'),
('aws-step-functions', @cat_id, 1, '複数のAWSサービスを調整し、サーバーレスワークフローを構築するためのサービスは？', '正解はAWS Step Functionsです。Lambda関数などを組み合わせたビジネスロジックを、ステートマシンとして視覚的に定義・実行できます。'),
('aws-eventbridge-bus', @cat_id, 1, 'アプリケーション、AWSサービス、SaaSアプリケーションからのデータを使用してイベント駆動型アーキテクチャを構築するサービスは？', '正解はAmazon EventBridgeです。CloudWatch Eventsの進化版であり、カスタムイベントバスやスキーマレジストリ機能を提供します。'),
('aws-redshift-dw', @cat_id, 1, 'ペタバイト規模の構造化データを分析できる、高速なフルマネージド型データウェアハウスは？', '正解はAmazon Redshiftです。SQLを使用して大規模なデータセットに対して複雑なクエリを高速に実行できます。'),
('aws-athena-sql', @cat_id, 1, 'S3内のデータに対して、標準SQLを使用して直接クエリを実行できるインタラクティブな分析サービスは？', '正解はAmazon Athenaです。サーバーレスであり、データのロード不要でS3上のCSVやJSONなどを直接分析できます。'),
('aws-glue-etl', @cat_id, 1, 'データの抽出、変換、ロード（ETL）を行うための完全マネージド型サービスは？', '正解はAWS Glueです。データカタログを作成し、分析のためにデータを準備・変換する作業を自動化します。'),
('aws-kinesis-streaming', @cat_id, 1, 'リアルタイムの動画やデータストリームを収集、処理、分析するためのプラットフォームは？', '正解はAmazon Kinesisです。Kinesis Data StreamsやKinesis Data Firehoseなどがあり、大量のストリーミングデータを扱えます。'),
('aws-cognito-auth', @cat_id, 1, 'Webおよびモバイルアプリにユーザーのサインアップ、サインイン、アクセス制御機能を追加するサービスは？', '正解はAmazon Cognitoです。ユーザープールによる独自ID管理や、Facebook/GoogleなどのソーシャルIDプロバイダーとの連携が可能です。'),
('aws-api-gateway', @cat_id, 1, '開発者がAPIを作成、公開、保守、監視、保護するための完全マネージド型サービスは？', '正解はAmazon API Gatewayです。RESTful APIやWebSocket APIを作成し、バックエンドのLambdaやEC2への入り口として機能します。'),
('aws-systems-manager', @cat_id, 1, 'AWS上のインフラストラクチャを可視化し、運用タスクを自動化するための統合管理サービスは？', '正解はAWS Systems Manager (SSM)です。パッチ適用、パラメータストアによる設定管理、インスタンスへのリモート接続（Session Manager）などの機能を提供します。'),
('aws-secrets-manager', @cat_id, 1, 'データベースの認証情報やAPIキーなどの機密情報を保護・管理し、ローテーションするサービスは？', '正解はAWS Secrets Managerです。コードにハードコーディングすることなく、アプリケーションから安全に機密情報を取得できます。'),
('aws-codecommit-git', @cat_id, 1, 'プライベートなGitリポジトリをホストする、完全マネージド型のソース管理サービスは？', '正解はAWS CodeCommitです。GitHubのようにGitベースのリポジトリを提供し、セキュアにコードを保存・バージョン管理できます。'),
('aws-codepipeline-ci-cd', @cat_id, 1, '迅速で信頼性の高いアプリケーションの更新を実現するための、継続的デリバリー（CI/CD）サービスは？', '正解はAWS CodePipelineです。ソースコードの変更からビルド、テスト、デプロイまでのリリースプロセスを自動化します。'),

-- 46-50: Amazon IVS (Interactive Video Service)
('aws-ivs-overview', @cat_id, 1, 'Amazon Interactive Video Service (Amazon IVS) の主な用途として最も適切なものは？', '正解は「低レイテンシーのインタラクティブなライブストリーミング」です。Twitchと同じ技術基盤を使用しており、視聴者とのリアルタイムな対話が必要なライブコマースや投票イベントなどに最適です。'),
('aws-ivs-latency', @cat_id, 1, 'Amazon IVSが提供する「超低レイテンシー（Ultra-low latency）」の遅延時間の目安は？', '正解は「3秒未満」です。従来のHLS配信では20〜30秒程度の遅延が発生することが多いですが、IVSは独自の技術により数秒以内の遅延を実現し、配信者と視聴者のスムーズなコミュニケーションを可能にします。'),
('aws-ivs-timed-metadata', @cat_id, 1, 'Amazon IVSにおいて、映像と同期してデータを視聴者アプリに送信し、投票フォームや商品情報を表示させる機能を何と呼ぶか？', '正解は「Timed Metadata（時限メタデータ）」です。動画ストリーム内にメタデータを埋め込むことで、特定のタイミングでクライアントアプリ側のアクションを発火させることができます。'),
('aws-ivs-ingest-protocol', @cat_id, 1, 'Amazon IVSに映像を送信（インジェスト）する際に使用する標準的なプロトコルは？', '正解はRTMP（Real-Time Messaging Protocol）またはRTMPSです。OBS Studioなどの一般的なストリーミングソフトウェアから、IVSのインジェストサーバーに向けて映像を配信します。'),
('aws-ivs-chat', @cat_id, 1, 'Amazon IVSと統合して使用できる、ライブ配信に特化したチャット機能を提供する機能は？', '正解はAmazon IVS Chatです。スケーラブルなチャットルーム管理、メッセージのモデレーション、認証機能などを提供し、ライブ動画の横でリアルタイムなコミュニケーションを実現します。');


-- --------------------------------------------------------
-- 4. 選択肢の登録（ランダムシャッフル版）
-- --------------------------------------------------------

INSERT INTO quiz_choice (quiz_id, choice_text, is_correct, display_order) VALUES
(@quiz_start + 0, 'AWS Lambda', 0, 1),
(@quiz_start + 0, 'Amazon EC2', 1, 2),
(@quiz_start + 0, 'Amazon S3', 0, 3),
(@quiz_start + 0, 'Amazon RDS', 0, 4),
(@quiz_start + 1, 'ブロックストレージ', 0, 1),
(@quiz_start + 1, 'オブジェクトストレージ', 1, 2),
(@quiz_start + 1, 'インメモリデータベース', 0, 3),
(@quiz_start + 1, 'ファイルストレージ', 0, 4),
(@quiz_start + 2, '無制限のストレージ容量', 0, 1),
(@quiz_start + 2, 'サーバーレス実行環境', 0, 2),
(@quiz_start + 2, 'OSへのフルアクセス権限', 0, 3),
(@quiz_start + 2, '管理タスクの自動化', 1, 4),
(@quiz_start + 3, 'Amazon EC2', 0, 1),
(@quiz_start + 3, 'AWS Lambda', 1, 2),
(@quiz_start + 3, 'AWS Batch', 0, 3),
(@quiz_start + 3, 'Amazon ECS', 0, 4),
(@quiz_start + 4, 'Amazon VPC', 1, 1),
(@quiz_start + 4, 'AWS Direct Connect', 0, 2),
(@quiz_start + 4, 'Amazon Route 53', 0, 3),
(@quiz_start + 4, 'Amazon VPN', 0, 4),
(@quiz_start + 5, 'IAMユーザー', 0, 1),
(@quiz_start + 5, 'IAMロール', 1, 2),
(@quiz_start + 5, 'IAMグループ', 0, 3),
(@quiz_start + 5, 'IAMポリシー', 0, 4),
(@quiz_start + 6, 'Amazon EFS', 0, 1),
(@quiz_start + 6, 'Amazon S3 Standard', 0, 2),
(@quiz_start + 6, 'Amazon S3 Glacier', 1, 3),
(@quiz_start + 6, 'Amazon EBS Cold HDD', 0, 4),
(@quiz_start + 7, 'AWS Direct Connect', 0, 1),
(@quiz_start + 7, 'AWS Global Accelerator', 0, 2),
(@quiz_start + 7, 'Amazon CloudFront', 1, 3),
(@quiz_start + 7, 'Amazon Route 53', 0, 4),
(@quiz_start + 8, 'Amazon CloudFront', 0, 1),
(@quiz_start + 8, 'AWS Transit Gateway', 0, 2),
(@quiz_start + 8, 'Elastic Load Balancing', 0, 3),
(@quiz_start + 8, 'Amazon Route 53', 1, 4),
(@quiz_start + 9, 'Amazon Redshift', 0, 1),
(@quiz_start + 9, 'Amazon RDS', 0, 2),
(@quiz_start + 9, 'Amazon Neptune', 0, 3),
(@quiz_start + 9, 'Amazon DynamoDB', 1, 4),
(@quiz_start + 10, 'Elastic Load Balancing', 1, 1),
(@quiz_start + 10, 'Amazon Route 53', 0, 2),
(@quiz_start + 10, 'AWS Global Accelerator', 0, 3),
(@quiz_start + 10, 'Auto Scaling', 0, 4),
(@quiz_start + 11, 'AWS Lambda', 0, 1),
(@quiz_start + 11, 'Amazon EC2 Auto Scaling', 1, 2),
(@quiz_start + 11, 'Amazon CloudWatch', 0, 3),
(@quiz_start + 11, 'Elastic Load Balancing', 0, 4),
(@quiz_start + 12, 'AWS CloudTrail', 0, 1),
(@quiz_start + 12, 'AWS X-Ray', 0, 2),
(@quiz_start + 12, 'Amazon CloudWatch', 1, 3),
(@quiz_start + 12, 'AWS Config', 0, 4),
(@quiz_start + 13, 'Amazon Inspector', 0, 1),
(@quiz_start + 13, 'AWS Artifact', 0, 2),
(@quiz_start + 13, 'AWS CloudTrail', 1, 3),
(@quiz_start + 13, 'Amazon CloudWatch', 0, 4),
(@quiz_start + 14, 'Amazon MQ', 0, 1),
(@quiz_start + 14, 'Amazon SES', 0, 2),
(@quiz_start + 14, 'Amazon SNS', 0, 3),
(@quiz_start + 14, 'Amazon SQS', 1, 4),
(@quiz_start + 15, 'Amazon Pinpoint', 0, 1),
(@quiz_start + 15, 'Amazon SES', 0, 2),
(@quiz_start + 15, 'Amazon SQS', 0, 3),
(@quiz_start + 15, 'Amazon SNS', 1, 4),
(@quiz_start + 16, 'Amazon DynamoDB', 0, 1),
(@quiz_start + 16, 'Amazon Neptune', 0, 2),
(@quiz_start + 16, 'Amazon RDS', 0, 3),
(@quiz_start + 16, 'Amazon ElastiCache', 1, 4),
(@quiz_start + 17, 'Amazon Aurora', 1, 1),
(@quiz_start + 17, 'Amazon RDS for Oracle', 0, 2),
(@quiz_start + 17, 'Amazon Redshift', 0, 3),
(@quiz_start + 17, 'Amazon DynamoDB', 0, 4),
(@quiz_start + 18, 'AWS WAF', 0, 1),
(@quiz_start + 18, 'AWS Shield', 0, 2),
(@quiz_start + 18, 'AWS IAM', 0, 3),
(@quiz_start + 18, 'AWS KMS', 1, 4),
(@quiz_start + 19, 'ファイアウォールの設定', 0, 1),
(@quiz_start + 19, '顧客データ', 0, 2),
(@quiz_start + 19, 'クラウド自体のセキュリティ', 1, 3),
(@quiz_start + 19, 'OSのパッチ適用', 0, 4),
(@quiz_start + 20, 'リージョナルキャッシュ', 0, 1),
(@quiz_start + 20, 'VPCエンドポイント', 0, 2),
(@quiz_start + 20, 'エッジロケーション', 0, 3),
(@quiz_start + 20, 'アベイラビリティーゾーン (AZ)', 1, 4),
(@quiz_start + 21, 'Amazon S3', 0, 1),
(@quiz_start + 21, 'Amazon FSx', 0, 2),
(@quiz_start + 21, 'Amazon EBS', 1, 3),
(@quiz_start + 21, 'Amazon EFS', 0, 4),
(@quiz_start + 22, 'Amazon S3', 0, 1),
(@quiz_start + 22, 'Instance Store', 0, 2),
(@quiz_start + 22, 'Amazon EBS', 0, 3),
(@quiz_start + 22, 'Amazon EFS', 1, 4),
(@quiz_start + 23, 'AWS Macie', 0, 1),
(@quiz_start + 23, 'AWS WAF', 0, 2),
(@quiz_start + 23, 'AWS Shield', 1, 3),
(@quiz_start + 23, 'Amazon GuardDuty', 0, 4),
(@quiz_start + 24, 'AWS Shield', 0, 1),
(@quiz_start + 24, 'AWS WAF', 1, 2),
(@quiz_start + 24, 'Security Groups', 0, 3),
(@quiz_start + 24, 'Network ACL', 0, 4),
(@quiz_start + 25, 'Amazon GuardDuty', 0, 1),
(@quiz_start + 25, 'AWS Config', 0, 2),
(@quiz_start + 25, 'Amazon Inspector', 1, 3),
(@quiz_start + 25, 'AWS Trusted Advisor', 0, 4),
(@quiz_start + 26, 'AWS CloudTrail', 0, 1),
(@quiz_start + 26, 'AWS Systems Manager', 0, 2),
(@quiz_start + 26, 'AWS Trusted Advisor', 1, 3),
(@quiz_start + 26, 'AWS Config', 0, 4),
(@quiz_start + 27, 'AWS Cost Explorer', 1, 1),
(@quiz_start + 27, 'Cost and Usage Report', 0, 2),
(@quiz_start + 27, 'AWS Budgets', 0, 3),
(@quiz_start + 27, 'AWS Billing Dashboard', 0, 4),
(@quiz_start + 28, 'AWS Cost Explorer', 0, 1),
(@quiz_start + 28, 'AWS Budgets', 1, 2),
(@quiz_start + 28, 'AWS Trusted Advisor', 0, 3),
(@quiz_start + 28, 'CloudWatch Alarms', 0, 4),
(@quiz_start + 29, 'AWS Directory Service', 0, 1),
(@quiz_start + 29, 'AWS Organizations', 1, 2),
(@quiz_start + 29, 'AWS Control Tower', 0, 3),
(@quiz_start + 29, 'AWS IAM', 0, 4),
(@quiz_start + 30, 'Amazon EKS', 0, 1),
(@quiz_start + 30, 'AWS Lambda', 0, 2),
(@quiz_start + 30, 'Amazon ECR', 0, 3),
(@quiz_start + 30, 'Amazon ECS', 1, 4),
(@quiz_start + 31, 'AWS Batch', 0, 1),
(@quiz_start + 31, 'AWS Fargate', 1, 2),
(@quiz_start + 31, 'AWS Outposts', 0, 3),
(@quiz_start + 31, 'Amazon EC2', 0, 4),
(@quiz_start + 32, 'Amazon ECS', 0, 1),
(@quiz_start + 32, 'AWS Fargate', 0, 2),
(@quiz_start + 32, 'Amazon EKS', 1, 3),
(@quiz_start + 32, 'Amazon ECR', 0, 4),
(@quiz_start + 33, 'AWS Batch', 0, 1),
(@quiz_start + 33, 'Amazon SWF', 0, 2),
(@quiz_start + 33, 'AWS Lambda', 0, 3),
(@quiz_start + 33, 'AWS Step Functions', 1, 4),
(@quiz_start + 34, 'Amazon SNS', 0, 1),
(@quiz_start + 34, 'Amazon EventBridge', 1, 2),
(@quiz_start + 34, 'Amazon SQS', 0, 3),
(@quiz_start + 34, 'Amazon Kinesis', 0, 4),
(@quiz_start + 35, 'Amazon DynamoDB', 0, 1),
(@quiz_start + 35, 'Amazon RDS', 0, 2),
(@quiz_start + 35, 'Amazon Redshift', 1, 3),
(@quiz_start + 35, 'Amazon Aurora', 0, 4),
(@quiz_start + 36, 'Amazon Athena', 1, 1),
(@quiz_start + 36, 'AWS Glue', 0, 2),
(@quiz_start + 36, 'Amazon Redshift', 0, 3),
(@quiz_start + 36, 'Amazon EMR', 0, 4),
(@quiz_start + 37, 'AWS Batch', 0, 1),
(@quiz_start + 37, 'Amazon Kinesis', 0, 2),
(@quiz_start + 37, 'AWS Glue', 1, 3),
(@quiz_start + 37, 'AWS Data Pipeline', 0, 4),
(@quiz_start + 38, 'AWS Glue', 0, 1),
(@quiz_start + 38, 'Amazon SQS', 0, 2),
(@quiz_start + 38, 'Amazon Kinesis', 1, 3),
(@quiz_start + 38, 'Amazon AppFlow', 0, 4),
(@quiz_start + 39, 'AWS Directory Service', 0, 1),
(@quiz_start + 39, 'AWS IAM', 0, 2),
(@quiz_start + 39, 'Amazon Cognito', 1, 3),
(@quiz_start + 39, 'AWS SSO', 0, 4),
(@quiz_start + 40, 'Elastic Load Balancing', 0, 1),
(@quiz_start + 40, 'AWS AppSync', 0, 2),
(@quiz_start + 40, 'Amazon API Gateway', 1, 3),
(@quiz_start + 40, 'Amazon CloudFront', 0, 4),
(@quiz_start + 41, 'AWS Systems Manager', 1, 1),
(@quiz_start + 41, 'AWS OpsWorks', 0, 2),
(@quiz_start + 41, 'AWS CloudFormation', 0, 3),
(@quiz_start + 41, 'AWS Config', 0, 4),
(@quiz_start + 42, 'AWS KMS', 0, 1),
(@quiz_start + 42, 'AWS IAM', 0, 2),
(@quiz_start + 42, 'AWS Secrets Manager', 1, 3),
(@quiz_start + 42, 'AWS Systems Manager Parameter Store', 0, 4),
(@quiz_start + 43, 'AWS CodeDeploy', 0, 1),
(@quiz_start + 43, 'AWS CodeStar', 0, 2),
(@quiz_start + 43, 'AWS CodeBuild', 0, 3),
(@quiz_start + 43, 'AWS CodeCommit', 1, 4),
(@quiz_start + 44, 'AWS CodePipeline', 1, 1),
(@quiz_start + 44, 'AWS X-Ray', 0, 2),
(@quiz_start + 44, 'AWS Step Functions', 0, 3),
(@quiz_start + 44, 'Amazon CloudWatch', 0, 4),
(@quiz_start + 45, '低レイテンシーのインタラクティブなライブストリーミング', 1, 1),
(@quiz_start + 45, 'テレビ会議システム', 0, 2),
(@quiz_start + 45, '監視カメラ映像の保存', 0, 3),
(@quiz_start + 45, '高解像度のビデオオンデマンド配信', 0, 4),
(@quiz_start + 46, '1分以上', 0, 1),
(@quiz_start + 46, '3秒未満', 1, 2),
(@quiz_start + 46, '30秒程度', 0, 3),
(@quiz_start + 46, '遅延なし（0秒）', 0, 4),
(@quiz_start + 47, 'Timed Metadata', 1, 1),
(@quiz_start + 47, 'Video Tags', 0, 2),
(@quiz_start + 47, 'Active Signals', 0, 3),
(@quiz_start + 47, 'Stream Events', 0, 4),
(@quiz_start + 48, 'WebRTC', 0, 1),
(@quiz_start + 48, 'HLS', 0, 2),
(@quiz_start + 48, 'SRT', 0, 3),
(@quiz_start + 48, 'RTMP / RTMPS', 1, 4),
(@quiz_start + 49, 'Amazon Connect', 0, 1),
(@quiz_start + 49, 'Amazon IVS Chat', 1, 2),
(@quiz_start + 49, 'Amazon SNS', 0, 3),
(@quiz_start + 49, 'AWS Chatbot', 0, 4);